spring:
  application:
    name: account-service
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/accounts_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  # Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  # Security Configuration (Basic setup - will be enhanced later)
  security:
    basic:
      enabled: true

# Server Configuration
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED

# Application specific configurations
app:
  notification:
    url: https://httpstat.us/
  currency:
    supported:
      - EUR
      - USD
      - SEK
      - RUB
  exchange-rates:
    # Fixed exchange rates between supported currencies
    rates:
      EUR_USD: 1.08
      USD_EUR: 0.92
      EUR_SEK: 11.22
      SEK_EUR: 0.089
      EUR_RUB: 102.45
      RUB_EUR: 0.0098
      USD_SEK: 10.37
      SEK_USD: 0.096
      USD_RUB: 94.82
      RUB_USD: 0.0105
      SEK_RUB: 9.13
      RUB_SEK: 0.109

# SpringDoc OpenAPI Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

# Resilience4j Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      notificationService:
        registerHealthIndicator: true
        slidingWindowSize: 100
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 10
        waitDurationInOpenState: 10s
        automaticTransitionFromOpenToHalfOpenEnabled: true
  timelimiter:
    instances:
      notificationService:
        timeoutDuration: 5s
  retry:
    instances:
      notificationService:
        maxAttempts: 3
        waitDuration: 1s
        retryExceptions:
          - java.io.IOException
          - org.springframework.web.reactive.function.client.WebClientResponseException 