spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://prod-db-host:5432/prod_accounts_db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
  
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  
  flyway:
    enabled: true
    # url, user, password inherited from datasource settings

# Logging Configuration
logging:
  level:
    root: WARN
    com.cgi.bank.account: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN # Disable SQL logging
    org.hibernate.type.descriptor.sql: WARN

# Server Configuration
server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework # If behind reverse proxy/load balancer

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED
      probes:
        enabled: true # Enable Kubernetes liveness/readiness probes

# Security Configuration
security:
  # Production security settings would be defined here
  # For example, more restrictive CORS settings, CSRF protection, etc.

# Application Specific Configuration
app:
  notification:
    # Production notification service URL
    url: ${NOTIFICATION_URL:https://notification-service.example.com/notify} 