-- V1: Creates the core tables for accounts, balances, and transactions.

-- Accounts Table
CREATE TABLE accounts (
    account_id VARCHAR(36) PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0 -- For optimistic locking
);

COMMENT ON TABLE accounts IS 'Stores unique bank accounts.';
COMMENT ON COLUMN accounts.account_id IS 'Primary key, UUID generated by the application.';
COMMENT ON COLUMN accounts.version IS 'Optimistic locking version number.';


-- Balances Table
CREATE TABLE balances (
    id BIGSERIAL PRIMARY KEY,
    account_id VARCHAR(36) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    amount NUMERIC(19, 4) NOT NULL DEFAULT 0.0000,
    version BIGINT NOT NULL DEFAULT 0, -- For optimistic locking on individual balances
    CONSTRAINT fk_balances_account FOREIGN KEY (account_id)
        REFERENCES accounts (account_id) ON DELETE CASCADE, -- If account is deleted, balances are removed
    CONSTRAINT uq_balances_account_currency UNIQUE (account_id, currency) -- Ensure only one balance per currency per account
);

CREATE INDEX idx_balances_account_id ON balances (account_id); -- Index for joining/lookup by account

COMMENT ON TABLE balances IS 'Stores currency-specific balances for each account.';
COMMENT ON COLUMN balances.id IS 'Primary key for the balance entry.';
COMMENT ON COLUMN balances.account_id IS 'Foreign key referencing the account.';
COMMENT ON COLUMN balances.currency IS '3-letter currency code (ISO 4217).';
COMMENT ON COLUMN balances.amount IS 'Current balance amount for the currency (precision 19, scale 4).';
COMMENT ON COLUMN balances.version IS 'Optimistic locking version number for the balance row.';


-- Transactions Table
CREATE TABLE transactions (
    id BIGSERIAL PRIMARY KEY,
    account_id VARCHAR(36) NOT NULL,
    type VARCHAR(20) NOT NULL, -- DEPOSIT, WITHDRAWAL, EXCHANGE_FROM, EXCHANGE_TO
    currency VARCHAR(3) NOT NULL,
    amount NUMERIC(19, 4) NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, -- Use TIMESTAMPTZ for timezone awareness
    
    CONSTRAINT fk_transactions_account FOREIGN KEY (account_id)
        REFERENCES accounts (account_id) ON DELETE RESTRICT
);

CREATE INDEX idx_transactions_account_id ON transactions (account_id); -- Index for finding transactions by account
CREATE INDEX idx_transactions_account_timestamp ON transactions(account_id, timestamp); -- Index for efficient lookups by account and timestamp
CREATE INDEX idx_transactions_timestamp ON transactions (timestamp DESC); -- Index for ordering by time (descending typical)

COMMENT ON TABLE transactions IS 'Audit log of all account operations.';
COMMENT ON COLUMN transactions.id IS 'Primary key for the transaction entry.';
COMMENT ON COLUMN transactions.account_id IS 'Foreign key referencing the account involved.';
COMMENT ON COLUMN transactions.type IS 'Type of transaction (DEPOSIT, WITHDRAWAL, etc.).';
COMMENT ON COLUMN transactions.currency IS 'Currency involved in the transaction.';
COMMENT ON COLUMN transactions.amount IS 'Amount of the transaction.';
COMMENT ON COLUMN transactions.timestamp IS 'Timestamp when the transaction occurred (with timezone).';